services:
    Cwd\GridBundle\Adapter\DoctrineAdapter:
        calls:
            - [setDoctrineRegistry, ['@?doctrine']]
        tags: ['cwd_grid.adapter']

    Cwd\GridBundle\GridFactory:
        public: true
        arguments:
            - '@twig'
        calls:
            - [setTranslator, ['@?translator']]


    Cwd\GridBundle\Twig\GridExtension:
        arguments:
#            - "%cwd.fancygrid.config%"
        public: false
        tags:
            - { name: twig.extension }

    test.twig.extension.pagerfanta:
        alias: twig.extension.pagerfanta
        public: true